### ISSUE TITLE
XEUS_ZMQ_DISABLE_ARCH_NATIVE option, redundant XEUS_ZMQ_BUILD_TESTS option line

### ISSUE THREAD

**Issue by topazus** [jupyter-xeus/xeus-zmq#21]
The two lines are the same, so one of them is redundant that needs to be removed.

https://github.com/jupyter-xeus/xeus-zmq/blob/e3f7d06d7e6f169b9d259f28474274df4d5bba16/CMakeLists.txt#L54-L57

I wonder what the `XEUS_ZMQ_DISABLE_ARCH_NATIVE` option do? I do not find the usage of it.

https://github.com/jupyter-xeus/xeus-zmq/blob/e3f7d06d7e6f169b9d259f28474274df4d5bba16/CMakeLists.txt#L75-L79

**Comment by JohanMabille** [comment]
Indeed we can remove one of the `XEUS_ZMQ_BUILD_TESTS` option. The `XEUS_ZQM_DISABLE_ARCH_NATIVE` is an oversight from a previous cleanup and cna be removed too. Would you like to open a PR?
