### ISSUE TITLE
Hide ZMQ entirely

### ISSUE THREAD

**Issue by SylvainCorlay** [jupyter-xeus/xeus-zmq#32]
In discussions with @JohanMabille and @RomainFrancois today, we realised it may be a good idea to remove any reference to zeromq in the public headers of xeus-zmq, so that downstream does bot need to link (directly) link with zeromq.

Doing this would probably require:

 1. hiding zmq using the pimpl patterns to hide the zmq types from the public headers.
 2. providing a function to instantiate the context from the xserver implementation.

For (1), this would break ABI (so minor version bump at least), and since we are removing public APIs it would be major version bump of xeus-zmq.

Then, in xeus kernels' cmake files, we could switch to `PRIVATE` in the call to `target_link_libraries(... xeus-zmq)`.

**Comment by bldrvnlw** [comment]
On a related point - when building xeus-zmq on Linux with static dependencies the assumption is that libsodium is required (see CMakeLists.txt line [`if (XEUS_ZMQ_STATIC_DEPENDENCIES AND NOT MSVC AND NOT APPLE)`](https://github.com/jupyter-xeus/xeus-zmq/blob/746abb611dd7717bb40d06702f52848ed81d5eb7/CMakeLists.txt#L176).

However it is possible to build libzmq without sodium using the flag WITH_LIBSODIUM OFF. AFAIK for a purely local application this is a valid option. So I'd really like to have a flag to inhibit sodium xeus-zmq use in this case. 

I'm not familiar with all the technical details here so if I'm missing something I apologize in advance for the noise.

**Comment by JohanMabille** [comment]
@bldrvnlw thanks for the pointer. We can definitely provide a flag for disabling libsodium in static builds of xeus-zmq; however, we won't be able to test it as we fetch ZeroMQ from conda-forge, and it is built with libsodium.

**Comment by JohanMabille** [comment]
Closing as this (i.e. hidding ZMQ) has been implemented. A new issue has been opened to track the libsodium inhibition request.
