### ISSUE TITLE
Could not find a configuration file for package "nlohmann_json" that exactly matches requested version "3.11".

### ISSUE THREAD

**Issue by Schamschula** [jupyter-xeus/xeus-zmq#39]
While rebuilding `xeus-zmq` against `xeus` 4.0.0 under MacPorts I get the following error:

> CMake Error at /opt/local/share/cmake-3.24/Modules/CMakeFindDependencyMacro.cmake:47 (find_package):
>   Could not find a configuration file for package "nlohmann_json" that
>   exactly matches requested version "3.11".
> 
>   The following configuration files were considered but not accepted:
> 
>   /opt/local/share/cmake/nlohmann_json/nlohmann_jsonConfig.cmake, version: 3.11.3
> 
> Call Stack (most recent call first):
>   /opt/local/lib/cmake/xeus/xeusConfig.cmake:52 (find_dependency)
>   CMakeLists.txt:88 (find_package)
> 
> 
> -- Configuring incomplete, errors occurred!

I have the following versions of `nlohmann-json` installed and active:

> marius@Mira ports % port installed nlohmann-json
> The following ports are currently installed:
>   nlohmann-json @3.11.2_0
>   nlohmann-json @3.11.3_0 (active)

**Comment by kaelingre** [comment]
The problem has been fixed in the following commit of xeus (unfortunately after version 4.0.0): https://github.com/jupyter-xeus/xeus/commit/20472921c9891767fa54d128b00480971f4ac057

**Comment by JohanMabille** [comment]
Indeed, this has been fixed in 4.0.1.
