### ISSUE TITLE
missing #include <optional> in xcontrol_runner.hpp

### ISSUE THREAD

**Issue by SandrineP** [jupyter-xeus/xeus-zmq#75]
This appears while running xeux-calc

**Comment by anutosh491** [comment]
Hmm, could you give a bit more context ? Like maybe what were you trying and what is the whole error you see ?

I see the following https://github.com/jupyter-xeus/xeus-zmq/blob/8ecc026ade0ec6af6d6d0b23879a25a7534300ca/include/xeus-zmq/xcontrol_runner.hpp#L13

**Comment by JohanMabille** [comment]
My fault, we were looking at a wrong version.
